### ISSUE TITLE
Incomplete error message

### ISSUE THREAD

**Issue by mnshgl0110** [schmeing/ReSeq#13]
Hi,

I am using the bioconda installation of ReSeq. When I try to run the `illuminaPE` command, I get the following error:
```
>>> 27-07-21 23:39:39: info:  60150316 (15%) were in an unmapped pair without adapters detected
!!! bool reseq::DataStats::SignsOfPairsWithNamesNotIdentical() [/opt/conda/conda-bld/reseq_1607076765868/work/reseq/DataStats.cpp:563]: error: Read names of reads from the same pair are not identical. Cannot continue.
Example position: 36177584:32669
Example read name: 0(� �'�DSXY:2:1165:32380:16986
```
I am not sure I get understand what this error mean. If two reads have different names then they would be different pairs, right? So, what is happening here? I am quite optimistic that the BAM file is correct and does not have discrepancies in read-names, so this is a bit surprising.

Still, it is great to have a clear error message, thanks for that. However, there is no read at the 36177584 position with 32380 or 16986 in the read name.
```
11:27 goel@pc-t7-095 goel:~$ samtools view $BAM CUR1G:36177580-36177590 | grep '32380'
11:27 goel@pc-t7-095 goel:~$ samtools view $BAM CUR1G:36177580-36177590 | grep '16989'
```
Also, the read-name is not properly decoded and shows binary characters. It would be really helpful in solving the issue if the exact position (chromosome:position) and the correct read-name is printed.

Thanks.

**Comment by schmeing** [comment]
Thank you for testing out this error message. I fixed the issue with the non-readable read name and improved the error message. I will push it to the devel branch once the run on a test dataset completes, to check if I introduce new problems. I will see to your installation issue next, so you can actually use the devel branch.

The position tells you the number of the reference sequence and the starting position of the read (both starting from 0). The error occurs because ReSeq could not find the other read from the pair (based on the name). So either they have different names or reads are missing. I would suggest you grep the whole bam file for "DSXY:2:1165:32380:16986" or wait until I fixed your installation issue and you get a better error message.

**Comment by schmeing** [comment]
Since the error message is fixed, I am closing the issue. Feel free to reopen it, if the bam file is correct and ReSeq is still crashing.
