### ISSUE TITLE
Sampling insert lengths did not find at least two usable lengths

### ISSUE THREAD

**Issue by andreirajkovic** [schmeing/ReSeq#14]
Downloaded fastqs from here https://www.ebi.ac.uk/ena/browser/view/SRX143960?show=reads

Build the reference using your data in the test folder
`bowtie2-build ecoli-GCF_000005845.2_ASM584v2_genomic.fa my_reference`

Map and Align the reads
`bowtie2 -p 32 -X 2000 -x my_reference -1 SRR490124_1.fastq.gz -2 SRR490124_2.fastq.gz | samtools sort -m 10G -@ 4 -T _tmp -o my_mappings.bam -`

Try and simulate the data
`reseq illuminaPE -j 8 -r ecoli-GCF_000005845.2_ASM584v2_genomic.fa -b /data/my_mappings.bam -1 my_simulated_data_1.fq -2 my_simulated_data_2.fq --adapterFile /ReSeq/adapters/TruSeq_single.fa --adapterMatrix /ReSeq/adapters/TruSeq_single.mat`

Error 
```
!!! bool reseq::InsertLengthSpline::GetSamplePositions(const reseq::Vect<long unsigned int>&) [/ReSeq/reseq/FragmentDistributionStats.cpp:1686]: error: Sampling insert lengths did not find at least two usable lengths.
!!! bool reseq::Simulator::Simulate(const char*, const char*, reseq::Reference&, reseq::DataStats&, const reseq::ProbabilityEstimates&, reseq::uintNumThreads, reseq::uintSeed, reseq::uintFragCount, double, reseq::RefSeqBiasSimulation, const string&, const string&, const string&, const string&, const string&) [/ReSeq/reseq/Simulator.cpp:2844]: error: An error occurred in the process: Terminating simulation
```

**Comment by schmeing** [comment]
Thank you for the detailed report, but unfortunately I could not reproduce the issue.
I followed your workflow except of redownloading the data and reference, because as you most likely know, they are already one of my test cases.
One thing I noticed is that you are providing absolute paths instead of relative and the positions are unlikely to contain the files, but I assume you shortened the paths for the post and if the files cannot be found or are problematic you should get errors before. Anyways, to use the provided adapters `--adapterFile TruSeq_single` should be enough.
I used the latest version of the devel branch for the test, but since it is one of my test cases it is unlikely (not impossible, since you skipped some of the preprocessing) that the errors occur with a different version.

I suggest you check if your downloaded files are complete and correct. If this is the case, you can send me an email and I can provide you with my files (.bam/.reseq/.reseq.ipf) and you can check if the simulation step still crashes using those and if that is not the case if the whole pipeline crashes starting from my bam file. This might provide insight into where our results are diverging.

Even if this turns out to not be a bug in the software I would be interested to hear, why it occurred, to improve the error message and help other users with the same issue.

**Comment by andreirajkovic** [comment]
I actually provided the wrong mapping and alignment commands:

```
zcat SRR490124_1.fastq.gz | head n400 > SRR490124_1_400.fastq
zcat SRR490124_2.fastq.gz | head n400 > SRR490124_2_400.fastq
```

`bowtie2 -p 32 -X 2000 -x my_reference -1 SRR490124_1_400.fastq -2 SRR490124_2_400.fastq | samtools sort -m 10G -@ 4 -T _tmp -o my_mappings.bam -
`

When I don't subsample the fastq, the software works just fine.

**Comment by schmeing** [comment]
I am not surprised that something crashes with just 100 reads. I never tested it, because crash or not the results will not be good. It is simply not enough data to extract proper statistics. What are you trying to achieve with this drastic downsampling? Or if this was just a test for low number of reads, what is your use case?

**Comment by andreirajkovic** [comment]
It was purely to test using a low number of reads. Thank you for following up with my question.

**Comment by schmeing** [comment]
Thank you. I added the information about issues with very low number of reads to the error message.
