### ISSUE TITLE
RNAseq data

### ISSUE THREAD

**Issue by ramesh8v** [schmeing/ReSeq#15]
Hello,

Thanks for developing this tool. Would it be possible to simulate RNA-Seq reads? I have bam files mapped using the STAR aligner.  Thanks.

**Comment by schmeing** [comment]
Hi,
it is currently not directly supported and I have never tested it. That said, there are two ways of getting RNA-Seq reads, but I do not know about the quality of the simulation for either strategy. So you would need to try yourself:

1. The simplest way is to train on DNA-Seq (or use a pretrained profile from the other repo if it fits) and then use the Transcriptome as input template for the simulation. You can use the "--refBiasFile" parameter to include the information about expression, but keep in mind that the reference bias is still modified by other biases like GC. Thus, if you put in the observed expressions, you will not get them back exactly.

2. The alternative is to map against the transcriptome (so your STAR mapping unfortunately does not help) and use this for the training (also providing the transcriptome as reference). You should use "--minMapQ 0", because due to the exons expressed in multiple transcripts you will have many reads with mapping quality 0, that you do not want to exclude. I hope for the transcriptome you can get away with not filtering repeats properly. This approach has the advantage that you extract biases specific to RNA-Seq and you also get the reference biases that give you the underlying expression and thus if you use them you will get the observed expression from the simulation. If you want to input other expressions you can still specify the "--refBiasFile" and use the ratio of the underlying expression and the observed expression as a correction factor. The downside is that this is completely untested and might go horribly wrong, so you better check if things make sense.
