### ISSUE TITLE
Generating exomes?

### ISSUE THREAD

**Issue by tinyheero** [schmeing/ReSeq#3]
Hi there,

Is it possible to use ReSeq to generate an exome? 

Kind regards,

Fong

**Comment by schmeing** [comment]
You can specify the exom as a fasta reference to simulate it. Using `--refBiasFile` you can control the coverage for the individual scaffolds/exons. It is planned but not yet implemented to generate targeted sequencing by providing the full genome and the target information.

**Comment by tinyheero** [comment]
Thanks for that information.

I am interested in potentially using it to introduce copy number alternations (e.g. having a region sampled at a higher proportion.  The `--refBiasFile` parameter looks like it could be used for that. Is there further documentation on how to use that parameter (i.e. the format)?

**Comment by schmeing** [comment]
If you want to have copy number variations on whole scaffolds (exons if you specify the exome as reference) then the `--refBiasFile` parameter is the way to go. For cnv within a scaffold you can specify the additional sequence in a vcf and use the `-V` parameter or create an additional scaffold for the additional sequence and use `--refBiasFile` again. Currently only one reference bias per scaffold is supported, but if need be I could quickly update that to allow for different reference biases per allele. Since the reference bias file will be automatically normalized, it is enough to specify:
```
exon1 1.0
exon2 3.5
exon3 2.0
```

**Comment by tinyheero** [comment]
Excellent. I assume that the values represent the relative bias to each other? Some in the above example exons 2 and 3 would have 3.5x and 2x more reads than exon1, respectively. In absolute copy number terms, one could interpret this as exons 2 and 3 having 3.5 and 2 copies?

**Comment by schmeing** [comment]
yes

**Comment by schmeing** [comment]
The new FAQ section added to the Readme in the devel branch summarizes this issue. Therefore, I will close this issue. Please, reopen it if there are further related questions or issues.
