### ISSUE TITLE
Exome sequencing profile and simulation

### ISSUE THREAD

**Issue by cilliannolan** [schmeing/ReSeq#9]
Hi there, 

I have a question regarding the workflow for simulating an exome (following on from https://github.com/schmeing/ReSeq/issues/3).

What is the recommended way to simulate an exome using ReSeq? 
Should the same FASTA file be used for building the ReSeq model as is used for simulating the reads? Or is it possible to build the model on the whole genome reference and simulate only over the exome space?
ie. modified from the workflow you describe:
```
reseq illuminaPE -j {num_jobs} -r reference.fa -b alignment.bam --vcfIn variant_sites.vcf --statsOnly
reseq illuminaPE -j {num_jobs} -s alignment.bam.reseq --stopAfterEstimation
reseq illuminaPE -j {num_jobs} -R exome_contigs.fa -s bam.reseq --ipfIterations 0 -1 read_pair_1.fq -2 read_pair_2.fq
```

When simulating reads using `exome_contigs.fa` , after building the ReSeq model using `reference.fa`, I received the following warning :
```
??? bool reseq::FragmentDistributionStats::UpdateRefSeqBias(reseq::RefSeqBiasSimulation, const string&, const reseq::Reference&, std::mt19937_64&) [/ReSeq/reseq/FragmentDistributionStats.cpp:3358]: warning: Cannot keep reference biases, because they don't match the reference. Will remove all reference biases. Reference has 172365 and there are 93 biases stored.
```

**Comment by schmeing** [comment]
It is possible to use a different reference. The only thing you cannot learn from a different reference is the reference sequence bias. Therefore, the warning message tells you that it simulates all exomes with the same probability (the number of reads still depends on the length of the exome). To turn off the warning, but keep this behaviour you can specify `--refBias no`. Otherwise you need to specify how likely the different exomes are related to each other with a reference bias file, which  you can specify with `--refBiasFile`.

**Comment by cilliannolan** [comment]
Great thank you so much for all the help.

Is it possible to specify a range of coordinates of the FASTA file on which to generate the ReSeq profile / to simulate from? 

The would be useful in my case as it would allow a sequence profile to be created using the exome FASTA without "lifting over" my `--vcfIn` variant file to the FASTA's new coordinate system (and allow me to use ReSeq's learned reference sequence bias rather than input a `reBiasFile`).

**Comment by schmeing** [comment]
Unfortunately, it is not yet possible. I understand that it makes things easier and I will implement it once I find the time, but since it is only a convenience feature it is not high on my priority list.
To use the learned reference sequence biases you can use the `reseq queryProfile --refSeqBias` command to output them and then duplicate the biases with adjusted names for as many exomes as you have on that sequence.

**Comment by cilliannolan** [comment]
That is perfectly understandable! Thanks for all your help.
